language: python
python:
  - "3.6"

cache: pip
install: "pip install -r requirements.txt"
script: python test.py

notifications:
  email:
    recipients:
      iel230@nyu.edu
    on_success: always
    on_failure: always


